# Generated by Django 5.2.7 on 2025-12-01 22:02

import src.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('board', models.JSONField(default=src.apps.core.models.empty_board)),
                ('game_over', models.BooleanField(default=False)),
                ('won', models.BooleanField(default=False)),
                ('finish_time', models.DateTimeField(null=True)),
                ('difficulty', models.CharField(choices=[('easy', '10-10-1'), ('medium', '16-16-40'), ('hard', '20-20-100')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
